title: Профсоюз работников ИТ
author:
 #  name: pinballwizard
 email: itunion@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
 Сайт профсоюза работников ИТ России
#baseurl: "" # the subpath of your site, e.g. /blog
#url: "http://itunion.pro" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
#theme: minima

minima:
 date_format: "%b %-d, %Y"
 skin: solarized-dark
 social_links:
  telegram: ruitunion
  facebook: itunionpro
  vkontakte: itunion_info
#  github: itunionpro
  rss: itunionpro

header_pages:
 - codex.md
 - about.md

plugins:
 - jekyll-feed
 - jekyll-seo-tag
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
